#!/bin/bash -xe

find /var/lib/jenkins/jobs -type d -name archive | while read a; do
    cd $a
    if [ ! -d logs ]; then
        continue
    fi

    job_and_num=$(bash -c '. ../injectedEnvVars.txt; echo "${JOB_NAME}/${BUILD_NUMBER}"')
    p="logs/$job_and_num"

    d="/ci/$p"
    if [ -d "$d" ]; then
        continue
    fi
    mkdir -p "$d"
    curl --insecure https://jenkins.a10cloud.com/job/${job_and_num}/consoleText > "$d/console_log.txt"
    tar cf - logs | tar xf - -C "$d"

    cd "$d"
    gunzip -r .
    cd - >/dev/null 2>&1

    cp $WORKSPACE/neutron-thirdparty-ci/README.md "$d"
done

exit 0
