#!/bin/bash -xe

find /var/lib/jenkins/jobs -type d -name archive | while read a; do
    cd $a
    p=$(bash -c '. ../injectedEnvVars.txt; echo "logs/${JOB_NAME}/${BUILD_NUMBER}"')

    if [ -d "/s3/$p" ]; then
        continue
    fi
    mkdir -p "/s3/$p"
    gzip -c ../log > "/s3/$p/console_log.txt.gz"
    tar cf - logs | tar xf - -C "/s3/$p"
done

exit 0
