#!/bin/bash -xe

find /var/lib/jenkins/jobs -type d -name archive | while read a; do
    cd $a
    p=$(bash -c '. ../injectedEnvVars.txt; echo "logs/${JOB_NAME}/${BUILD_NUMBER}"')

    d="/ci/$p"
    if [ -d "$d" ]; then
        continue
    fi
    mkdir -p "$d"
    cp ../log "$d/console_log.txt"
    tar cf - logs | tar xf - -C "$d"

    cd "$d"
    gunzip -r .
    cd - >/dev/null 2>&1
done

exit 0
