#!/bin/bash -xe

if [[ ! -e devstack-gate ]]; then
    git clone git://git.openstack.org/openstack-infra/devstack-gate
else
    cd devstack-gate
    git remote set-url origin git://git.openstack.org/openstack-infra/devstack-gate
    git remote update
    git reset --hard
    if ! git clean -x -f ; then
        sleep 1
        git clean -x -f
    fi
    git checkout master
    git reset --hard remotes/origin/master
    if ! git clean -x -f ; then
        sleep 1
        git clean -x -f
    fi
    cd ..
fi

rm -fr neutron-thirdparty-ci
git clone https://github.com/dougwig/neutron-thirdparty-ci
