#!/bin/bash -xe

if [ -z "$LOCKED" ]; then
    # Only one of us gets to run at a time
    (
        flock 9 || exit 1
        export LOCKED=1
        exec $0 $*
    ) 9>/tmp/copy-logs.lock
fi

if [ -f $WORKSPACE/neutron-thirdparty-ci/bin/strip_jenkins_log.rb ]; then
    strip=$WORKSPACE/neutron-thirdparty-ci/bin/strip_jenkins_log.rb
else
    strip=/home/builder/neutron-thirdparty-ci/neutron-thirdparty-ci/bin/strip_jenkins_log.rb
fi

find /var/lib/jenkins/jobs -type d -name archive | while read a; do
    cd $a
    if [ ! -d logs ]; then
        continue
    fi

    job=$(cat ../injectedEnvVars.txt | perl -ne '/^JOB_NAME=(.*)$/ && print "$1";')
    build_number=$(cat ../injectedEnvVars.txt | perl -ne '/^BUILD_NUMBER=(.*)$/ && print "$1";')
    gerrit_change=$(cat ../injectedEnvVars.txt | perl -ne '/^ZUUL_CHANGE=(.*)$/ && print "$1";')
    gerrit_patchset=$(cat ../injectedEnvVars.txt | perl -ne '/^ZUUL_PATCHSET=(.*)$/ && print "$1";')
    echo $job
    echo $build_number
    gerrit="$gerrit_change/$gerrit_patchset"
    echo $gerrit

    if [ "$job" = "a10-neutron-lbaas" ]; then
        job="a10-neutron-lbaas-wrapper"
    elif [ "$job" = "a10-neutron-lbaas-ec2" ]; then
        job="a10-neutron-lbaas"
    fi
    # When the lbaas and lbaas-ec2 jobs were out of sync, logs did not line up
    if [ -n "$build_number" -a $build_number -le 85 ]; then
        build_number=$((build_number-1))
    fi
    echo $job
    job_and_num="${job}/${build_number}"
    echo $job_with_num
    job_with_gerrit="${job}/${gerrit}/${build_number}"
    echo $job_with_gerrit

    p="logs/$job_with_gerrit"
    d="/ci/$p"
    if [ -d "$d" ]; then
        continue
    fi
    mkdir -p "$d"
    #curl --insecure https://jenkins.a10cloud.com/job/${job_and_num}/consoleText > "$d/console_log.txt"
    #cp ../log "$d/console_log.txt"
    $WORKSPACE/neutron-thirdparty-ci/bin/strip_jenkins_log.rb ../log > "$d/console_log.txt"
    gzip "$d/console_log.txt"
    tar cf - logs | tar xf - -C "$d"
    gzip -q -r "$d/logs"
    chmod -R a+r "$d"

    # Some browsers don't download gz seamlessly, and some folks don't like that.
    cd "$d"
    #gunzip -r .

    # Some CI info; who to call if it's broke.
    cp $WORKSPACE/neutron-thirdparty-ci/README.md "$d"

    # # In prep to switch to URLs that match gerrit, ish, start making them as links now.
    # x="logs/$job_with_gerrit"
    # b=$(dirname "/ci/$x")
    # mkdir -p $b
    # cd $b
    # ln -s "$d" .
done

exit 0
