#!/bin/bash -xe

if [ -z "$WORKSPACE" ]; then
    WORKSPACE=/home/builder
fi

if [ -n "$1" ]; then
    JOB_DIR="$1"
else
    JOB_DIR="/var/lib/jenkins/jobs/${JOB_NAME}/builds/$BUILD_NUMBER"
    cd $JOB_DIR

    # If this has a -ec2 child build, figure out where it is
    child=$($WORKSPACE/neutron-thirdparty-ci/bin/strip_jenkins_log.rb log | \
        perl -ne '/\-ec2 \#([0-9]+) completed/ && print "$1\n";')
    if [ -n "$child" ]; then
        PARENT_LOG="$JOB_DIR/log"
        JOB_DIR="/var/lib/jenkins/jobs/${JOB_NAME}-ec2/builds/$child"
    fi
fi
cd $JOB_DIR

job=$(cat injectedEnvVars.txt | perl -ne '/^JOB_NAME=(.*)$/ && print "$1";')
build_number=$(cat injectedEnvVars.txt | perl -ne '/^BUILD_NUMBER=(.*)$/ && print "$1";')
gerrit_change=$(cat injectedEnvVars.txt | perl -ne '/^ZUUL_CHANGE=(.*)$/ && print "$1";')
gerrit_patchset=$(cat injectedEnvVars.txt | perl -ne '/^ZUUL_PATCHSET=(.*)$/ && print "$1";')
echo $job
echo $build_number
gerrit="$gerrit_change/$gerrit_patchset"
echo $gerrit

if [ "$job" = "a10-neutron-lbaas" ]; then
    job="a10-neutron-lbaas-wrapper"
elif [ "$job" = "a10-neutron-lbaas-ec2" ]; then
    job="a10-neutron-lbaas"
fi
if [ "$job" = "a10-neutron-lbaasv2" ]; then
    job="a10-neutron-lbaasv2-wrapper"
elif [ "$job" = "a10-neutron-lbaasv2-ec2" ]; then
    job="a10-neutron-lbaasv2"
fi

echo $job
job_and_num="${job}/${build_number}"
echo $job_with_num
job_with_gerrit="${job}/${gerrit}/${build_number}"
echo $job_with_gerrit

p="logs/$job_with_gerrit"
d="/ci/$p"
if [ -d "$d" ]; then
    mv "$d" "$d.old"
fi
mkdir -p "$d"

$WORKSPACE/neutron-thirdparty-ci/bin/strip_jenkins_log.rb log > "$d/console_log.txt"
gzip "$d/console_log.txt"

if [ -n "$PARENT_LOG" ]; then
    $WORKSPACE/neutron-thirdparty-ci/bin/strip_jenkins_log.rb "$PARENT_LOG" > "$d/parent_log.txt"
    gzip "$d/parent_log.txt"
fi

if [ -d archive/logs ]; then
    cd archive
    tar cf - logs | tar xf - -C "$d"
    gzip -q -r "$d/logs"
    chmod -R a+r "$d"
fi

# Some CI info; who to call if it's broke.
cp $WORKSPACE/neutron-thirdparty-ci/README.md "$d"
