#!/bin/sh -x

# Override these in Jenkins for custom jobs

A10_APPLIANCE_AMI=${A10_APPLIANCE_AMI:-ami-835c0fb3}
A10_INSTANCE_TYPE=${A10_INSTANCE_TYPE:-m1.medium}
A10_KEY_NAME=${A10_KEY_NAME:-appliance-key}
A10_SECURITY_GROUP=${A10_SECURITY_GROUP:-appliance-group}
A10_SUBNET_ID=${A10_SUBNET_ID:-subnet-7360dd16}

t=/tmp/jenkins.a10.$$

# $ aws ec2 run-instances --image-id ami-xxxxxxxx --count 1 --instance-type t1.micro --key-name MyKeyPair --security-group-ids sg-xxxxxxxx --subnet-id subnet-xxxxxxxx

aws ec2 run-instances \
  --image-id $A10_APPLIANCE_AMI \
  --count 1 \
  --instance-type $A10_INSTANCE_TYPE \
  --key-name $A10_KEY_NAME \
  --security-group-ids $A10_SECURITY_GROUP \
  --subnet-id $A10_SUBNET_ID > $t

echo "Writing instance id to disk"
set +x
grep InstanceId $t | cut -f2 -d: | tr -d '"' > ~/.a10-instance-id
grep PrivateIpAddress $t | cut -f2 -d: | tr -d '"' > ~/.a10-private-ip
