#!/bin/bash -x

$WORKSPACE/neutron-thirdparty-ci/slave/ci-slave-cleanup

sudo rm -fr /opt/stack/logs.old
if [ -d /opt/stack/logs ]; then
  sudo mv /opt/stack/logs /opt/stack/logs.old
fi

cd /opt/stack/new
sudo rm -f devstacklog.txt*
sudo rm -fr screen-logs.old
sudo rm -f worlddump*
if [ -d screen-logs ]; then
  sudo mv screen-logs screen-logs.old
fi
sudo rm -fr neutron.old
if [ -d neutron ]; then
  sudo mv neutron neutron.old
fi
cd -

cd /var/log
sudo rm -fr apache2.old
sudo mv apache2 apache2.old
sudo mkdir apache2
sudo chown root.adm apache2
sudo chmod 750 apache2
cd -

sudo service rabbitmq-server restart

exit 0
