#!/bin/bash -xe

echo "Third-party pre-devstack hook"

sudo pip install -U acos-client
sudo pip install -U a10-neutron-lbaas

# Make sure we have a configuration

d=/etc/neutron/services/loadbalancer/a10networks
sudo mkdir -p $d
sudo cp $HOME/config.py $d/

exit 0
