#!/bin/bash -xe

if [ -d /opt/stack ]; then
    echo "ERROR: attempt to re-use devstack node"
    exit 1
fi

if [ -z $ZUUL_PROJECT ]; then
    export ZUUL_PROJECT=openstack/neutron
fi
if [ -z $ZUUL_BRANCH ]; then
    export ZUUL_BRANCH=master
fi
export ZUUL_URL=http://zuul.a10cloud.com/p

echo "HOSTNAME `hostname`"

sudo $WORKSPACE/neutron-thirdparty-ci/slave/make-swap

function function_exists {
    type $1 2>/dev/null | grep -q 'is a function'
}

if [ "$LBAAS_VERSION" = "2" ]; then
  . neutron-thirdparty-ci/slave/run-v2
else
  . neutron-thirdparty-ci/slave/run-v1
fi

if ! function_exists "pre_test_hook"; then
  function pre_test_hook {
    $WORKSPACE/neutron-thirdparty-ci/slave/pre-test-hook
    return $?
  }
  export -f pre_test_hook
fi

if ! function_exists "pre_setup_hook"; then
  function pre_setup_hook {
    $WORKSPACE/neutron-thirdparty-ci/slave/pre-setup-hook
    return $?
  }
  export -f pre_setup_hook
fi

if ! function_exists "post_cleanup_hook"; then
  function post_cleanup_hook {
    $WORKSPACE/neutron-thirdparty-ci/slave/post-cleanup-hook
    return $?
  }
  export -f post_cleanup_hook
fi

export RE_EXEC=true
pre_setup_hook
cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
set +e
bash ./safe-devstack-vm-gate-wrap.sh
r=$?
post_cleanup_hook
exit $r
