#!/bin/sh

set -x

if [ `uname` != "Linux" ]; then
	echo "ERROR: linux only"
	exit 1
fi

if [ `whoami` != "root" ]; then
	echo "ERROR: must be root"
	exit 1
fi

z=`swapon -s | grep -v Filename`
if [ -n "$z" ]; then
	echo "ERROR: swap already exists"
	exit 1
fi

set -e

size_in_kb="10485760"

dd if=/dev/zero of=/swapfile bs=1024 count="$size_in_kb"

chown root:root /swapfile 
chmod 0600 /swapfile

mkswap /swapfile
swapon /swapfile

cp /etc/fstab /etc/fstab.old
echo "/swapfile       none    swap    sw      0       0" >> /etc/fstab

swapon -s

exit 0



