#!/bin/bash -xe

if [ -d /opt/stack ]; then
    echo "ERROR: attempt to re-use devstack node"
    exit 1
fi

# sudo addgroup jenkins
# sudo adduser jenkins wheel

t=/tmp/.sudoers.$$
cat - > $t <<EOF
root ALL = (ALL) ALL
%wheel ALL = (ALL) NOPASSWD:ALL
jenkins ALL = (ALL) NOPASSWD:ALL
stack ALL = (ALL) NOPASSWD:ALL
EOF
sudo cp /etc/sudoers /etc/sudoers.dist
sudo chmod 440 $t
sudo mv $t /etc/sudoers

sudo apt-get install -y python python-pip
sudo pip install awscli

# sudo cp -r ~ubuntu/.aws ~
# sudo cp ~ubuntu/.license_sn ~
# sudo cp ~ubuntu/.ssh/id_rsa ~ubuntu/.ssh/id_rsa.pub ~/.ssh
# sudo chown -R `whoami` ~/.aws ~/.license_sn ~/.ssh
