#!/bin/bash -xe

if [ -d /opt/stack ]; then
    echo "ERROR: attempt to re-use devstack node"
    exit 1
fi

sudo addgroup jenkins
sudo adduser jenkins wheel
sudo adduser stack wheel

sudo cp -r ~ubuntu/.aws ~
sudo chown -R `whoami` ~/.aws
sudo cp ~ubuntu/.license_sn ~
sudo chown -R `whoami` ~/.license_sn

sudo apt-get install -y python python-pip
sudo pip install awscli

cat /etc/passwd
cat /etc/group
sudo cat /etc/sudoers
