#!/bin/bash -xe

if [ -d /opt/stack ]; then
    echo "ERROR: attempt to re-use devstack node"
    exit 1
fi

sudo addgroup jenkins

sudo cp -r ~ubuntu/.aws ~
sudo chown -R `whoami` ~/.aws
sudo cp ~ubuntu/.license_sn ~
sudo chown -R `whoami` ~/.license_sn

sudo apt-get install -y python python-pip >/tmp/apt.out
sudo pip install awscli >/tmp/pip.out
