#!/bin/bash -xe

export PYTHONUNBUFFERED=true
export DEVSTACK_GATE_TIMEOUT=120
export DEVSTACK_GATE_TEMPEST=1
export DEVSTACK_GATE_TEMPEST_NOTESTS=1
export DEVSTACK_GATE_EXERCISES=0
export DEVSTACK_GATE_NEUTRON=1
export DEVSTACK_GATE_INSTALL_TESTONLY=1
export BRANCH_OVERRIDE={branch-override}
if [ "$BRANCH_OVERRIDE" != "default" ] ; then
    export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
fi

function gate_hook {{
    /opt/stack/new/neutron-lbaas/neutron_lbaas/tests/contrib/gate_hook.sh
}}
export -f gate_hook

function post_test_hook {{
    /opt/stack/new/neutron-lbaas/neutron_lbaas/tests/contrib/post_test_hook.sh
}}
export -f post_test_hook
