#!/bin/bash -xe

#!/bin/bash -xe

export PYTHONUNBUFFERED=true
export DEVSTACK_GATE_TIMEOUT=120
export DEVSTACK_GATE_TEMPEST=1
export DEVSTACK_GATE_TEMPEST_NOTESTS=1
export DEVSTACK_GATE_EXERCISES=0
export DEVSTACK_GATE_NEUTRON=1
export DEVSTACK_GATE_INSTALL_TESTONLY=1
# export BRANCH_OVERRIDE={branch-override}
# if [ "$BRANCH_OVERRIDE" != "default" ] ; then
#     export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
# fi

# exclusions
. $WORKSPACE/neutron-thirdparty-ci/slave/v1-testcases


function gate_hook {
    /opt/stack/new/neutron-lbaas/neutron_lbaas/tests/contrib/gate_hook.sh lbaasv1
}
export -f gate_hook

function post_test_hook {
    set +e
    echo "LBAAS TEMPEST CONF"
    cat /opt/stack/new/neutron-lbaas/neutron_lbaas/tests/tempest/etc/tempest.conf
    echo "TEMPEST CONF"
    cat /opt/stack/new/tempest/etc/tempest.conf
    echo "GREP"
    grep api_exten /opt/stack/new/tempest/etc/tempest.conf
    echo "HOOK TIME"
    set -e
    f=/opt/stack/new/tempest/etc/tempest.conf
    sudo mv $f $f.old
    sudo touch $f
    sudo chmod a+rwx $f
    cat $f.old | sed -e 's/\#api_extensions = all/api_extensions = lbaas/' > $f
    /opt/stack/new/neutron-lbaas/neutron_lbaas/tests/contrib/post_test_hook.sh lbaasv1
}
export -f post_test_hook
